export const previewBlockSchemas = [
  {
    type: "Profile",
    blockTitle: "PROFILE",
    showBlockTitle: false,
    showItemTitle: true,
    showItemSubTitle: true,
    showItemDescript: true,
    showItemStartEndTime: false,
    showItemEndTime: false,
    showItemLink: false,
  },
  {
    type: "Education",
    blockTitle: "EDUCATION",
    showBlockTitle: false,
    showItemTitle: true,
    showItemSubTitle: true,
    showItemDescript: true,
    showItemStartEndTime: false,
    showItemEndTime: false,
    showItemLink: false,
  },
  {
    type: "Experience",
    blockTitle: "WORK & INTERNSHIP EXPERIENCE",
    showBlockTitle: false,
    showItemTitle: true,
    showItemSubTitle: true,
    showItemDescript: true,
    showItemStartEndTime: false,
    showItemEndTime: false,
    showItemLink: false,
  },
  {
    type: "Achievement",
    blockTitle: "ACADEMIC ACHIEVEMENTS",
    showBlockTitle: false,
    showItemTitle: true,
    showItemSubTitle: true,
    showItemDescript: true,
    showItemStartEndTime: false,
    showItemEndTime: false,
    showItemLink: false,
  },
  {
    type: "Project",
    blockTitle: "PROJECT & PORTFOLIO",
    showBlockTitle: false,
    showItemTitle: true,
    showItemSubTitle: true,
    showItemDescript: true,
    showItemStartEndTime: false,
    showItemEndTime: false,
    showItemLink: false,
  },
  {
    type: "Skill",
    blockTitle: "SKILLS",
    showBlockTitle: false,
    showItemTitle: true,
    showItemSubTitle: true,
    showItemDescript: true,
    showItemStartEndTime: false,
    showItemEndTime: false,
    showItemLink: false,
  },
];
